name: CI Pipeline

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Backend Image
        run: docker build -t backend:latest ./springboot/app

      - name: Build Frontend Image
        run: docker build -t frontend:latest ./angular-app

      - name: Push Backend Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

      - name: Push Frontend Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

      - name: Start application with Docker Compose
        run: docker-compose up -d

      - name: Check running containers
        run: docker ps

